# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /meetingroombookingmanage
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid连接池
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///conference
      username: root
      password: wjd3396815
  servlet:
    multipart:
      max-file-size: 1000MB # 设置单个文件的最大上传大小为1000MB
      max-request-size: 1000MB # 设置整个请求的最大上传大小为1000MB
  resources:
    static-locations: classpath:static/,file:static/
  data:
    redis:
      host: localhost
      port: 6379

# mybatis配置 - 彻底抛弃mybatis-config.xml
# 指定mapper的xml文件的位置、settings的配置、别名的配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml  # mapper的xml文件的位置
  type-aliases-package: com.conference.pojo # 包下所有实体类的别名
  configuration:
    map-underscore-to-camel-case: true # 开启下划线命名和驼峰式命名的自动转换
    auto-mapping-behavior: full # 开启列名和属性名的自动映射
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 开启日志输出